>>> from bible import *
>>> Ezra[2]
Ezra 2:1-70 (70 verses)
>>> Ezra[2][1].numbers()
[1]
>>> Ezra[2][1]
Ezra 2:1 Now these are the children of the province that went up out of the captivity, of those which had been carried away, whom Nebuchadnezzar the king of Babylon had carried away unto Babylon, and came again unto Jerusalem and Judah, every one unto his city;
>>> import bible
>>> Ezra[2]@(I+method.numbers)@p
(Ezra 2:1 Now these are the children of the province that went up out of the captivity, of those which had been carried away, whom Nebuchadnezzar the king of Babylon had carried away unto Babylon, and came again unto Jerusalem and Judah, every one unto his city;, [1])
(Ezra 2:2 Which came with Zerubbabel: Jeshua, Nehemiah, Seraiah, Reelaiah, Mordecai, Bilshan, Mizpar, Bigvai, Rehum, Baanah. The number of the men of the people of Israel:, [])
(Ezra 2:3 The children of Parosh, two thousand an hundred seventy and two., [2172])
(Ezra 2:4 The children of Shephatiah, three hundred seventy and two., [372])
(Ezra 2:5 The children of Arah, seven hundred seventy and five., [775])
(Ezra 2:6 The children of Pahathmoab, of the children of Jeshua and Joab, two thousand eight hundred and twelve., [2812])
(Ezra 2:7 The children of Elam, a thousand two hundred fifty and four., [1254])
(Ezra 2:8 The children of Zattu, nine hundred forty and five., [945])
(Ezra 2:9 The children of Zaccai, seven hundred and threescore., [760])
(Ezra 2:10 The children of Bani, six hundred forty and two., [642])
(Ezra 2:11 The children of Bebai, six hundred twenty and three., [623])
(Ezra 2:12 The children of Azgad, a thousand two hundred twenty and two., [1222])
(Ezra 2:13 The children of Adonikam, six hundred sixty and six., [666])
(Ezra 2:14 The children of Bigvai, two thousand fifty and six., [2056])
(Ezra 2:15 The children of Adin, four hundred fifty and four., [454])
(Ezra 2:16 The children of Ater of Hezekiah, ninety and eight., [98])
(Ezra 2:17 The children of Bezai, three hundred twenty and three., [323])
(Ezra 2:18 The children of Jorah, an hundred and twelve., [112])
(Ezra 2:19 The children of Hashum, two hundred twenty and three., [223])
(Ezra 2:20 The children of Gibbar, ninety and five., [95])
(Ezra 2:21 The children of Bethlehem, an hundred twenty and three., [123])
(Ezra 2:22 The men of Netophah, fifty and six., [56])
(Ezra 2:23 The men of Anathoth, an hundred twenty and eight., [128])
(Ezra 2:24 The children of Azmaveth, forty and two., [42])
(Ezra 2:25 The children of Kirjatharim, Chephirah, and Beeroth, seven hundred and forty and three., [743])
(Ezra 2:26 The children of Ramah and Gaba, six hundred twenty and one., [621])
(Ezra 2:27 The men of Michmas, an hundred twenty and two., [122])
(Ezra 2:28 The men of Bethel and Ai, two hundred twenty and three., [223])
(Ezra 2:29 The children of Nebo, fifty and two., [52])
(Ezra 2:30 The children of Magbish, an hundred fifty and six., [156])
(Ezra 2:31 The children of the other Elam, a thousand two hundred fifty and four., [1254])
(Ezra 2:32 The children of Harim, three hundred and twenty., [320])
(Ezra 2:33 The children of Lod, Hadid, and Ono, seven hundred twenty and five., [725])
(Ezra 2:34 The children of Jericho, three hundred forty and five., [345])
(Ezra 2:35 The children of Senaah, three thousand and six hundred and thirty., [3630])
(Ezra 2:36 The priests: the children of Jedaiah, of the house of Jeshua, nine hundred seventy and three., [973])
(Ezra 2:37 The children of Immer, a thousand fifty and two., [1052])
(Ezra 2:38 The children of Pashur, a thousand two hundred forty and seven., [1247])
(Ezra 2:39 The children of Harim, a thousand and seventeen., [1017])
(Ezra 2:40 The Levites: the children of Jeshua and Kadmiel, of the children of Hodaviah, seventy and four., [74])
(Ezra 2:41 The singers: the children of Asaph, an hundred twenty and eight., [128])
(Ezra 2:42 The children of the porters: the children of Shallum, the children of Ater, the children of Talmon, the children of Akkub, the children of Hatita, the children of Shobai, in all an hundred thirty and nine., [139])
(Ezra 2:43 The Nethinims: the children of Ziha, the children of Hasupha, the children of Tabbaoth,, [])
(Ezra 2:44 The children of Keros, the children of Siaha, the children of Padon,, [])
(Ezra 2:45 The children of Lebanah, the children of Hagabah, the children of Akkub,, [])
(Ezra 2:46 The children of Hagab, the children of Shalmai, the children of Hanan,, [])
(Ezra 2:47 The children of Giddel, the children of Gahar, the children of Reaiah,, [])
(Ezra 2:48 The children of Rezin, the children of Nekoda, the children of Gazzam,, [])
(Ezra 2:49 The children of Uzza, the children of Paseah, the children of Besai,, [])
(Ezra 2:50 The children of Asnah, the children of Mehunim, the children of Nephusim,, [])
(Ezra 2:51 The children of Bakbuk, the children of Hakupha, the children of Harhur,, [])
(Ezra 2:52 The children of Bazluth, the children of Mehida, the children of Harsha,, [])
(Ezra 2:53 The children of Barkos, the children of Sisera, the children of Thamah,, [])
(Ezra 2:54 The children of Neziah, the children of Hatipha., [])
(Ezra 2:55 The children of Solomon's servants: the children of Sotai, the children of Sophereth, the children of Peruda,, [])
(Ezra 2:56 The children of Jaalah, the children of Darkon, the children of Giddel,, [])
(Ezra 2:57 The children of Shephatiah, the children of Hattil, the children of Pochereth of Zebaim, the children of Ami., [])
(Ezra 2:58 All the Nethinims, and the children of Solomon's servants, were three hundred ninety and two., [392])
(Ezra 2:59 And these were they which went up from Telmelah, Telharsa, Cherub, Addan, and Immer: but they could not shew their father's house, and their seed, whether they were of Israel:, [])
(Ezra 2:60 The children of Delaiah, the children of Tobiah, the children of Nekoda, six hundred fifty and two., [652])
(Ezra 2:61 And of the children of the priests: the children of Habaiah, the children of Koz, the children of Barzillai; which took a wife of the daughters of Barzillai the Gileadite, and was called after their name:, [])
(Ezra 2:62 These sought their register among those that were reckoned by genealogy, but they were not found: therefore were they, as polluted, put from the priesthood., [])
(Ezra 2:63 And the Tirshatha said unto them, that they should not eat of the most holy things, till there stood up a priest with Urim and with Thummim., [])
(Ezra 2:64 The whole congregation together was forty and two thousand three hundred and threescore,, [42360])
(Ezra 2:65 Beside their servants and their maids, of whom there were seven thousand three hundred thirty and seven: and there were among them two hundred singing men and singing women., [7337, 200])
(Ezra 2:66 Their horses were seven hundred thirty and six; their mules, two hundred forty and five;, [736, 245])
(Ezra 2:67 Their camels, four hundred thirty and five; their asses, six thousand seven hundred and twenty., [435, 6720])
(Ezra 2:68 And some of the chief of the fathers, when they came to the house of the LORD which is at Jerusalem, offered freely for the house of God to set it up in his place:, [])
(Ezra 2:69 They gave after their ability unto the treasure of the work threescore and one thousand drams of gold, and five thousand pound of silver, and one hundred priests' garments., [61000, 5000, 100])
(Ezra 2:70 So the priests, and the Levites, and some of the people, and the singers, and the porters, and the Nethinims, dwelt in their cities, and all Israel in their cities., [])
[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
>>> Ezra[2:2:35].numbers()
[2172, 372, 775, 2812, 1254, 945, 760, 642, 623, 1222, 666, 2056, 454, 98, 323, 112, 223, 95, 123, 56, 128, 42, 743, 621, 122, 223, 52, 156, 1254, 320, 725, 345, 3630]
>>> sum(_)
24144
>>> Nehemiah[7]@(I+method.numbers)@p
(Nehemiah 7:1 Now it came to pass, when the wall was built, and I had set up the doors, and the porters and the singers and the Levites were appointed,, [])
(Nehemiah 7:2 That I gave my brother Hanani, and Hananiah the ruler of the palace, charge over Jerusalem: for he was a faithful man, and feared God above many., [])
(Nehemiah 7:3 And I said unto them, Let not the gates of Jerusalem be opened until the sun be hot; and while they stand by, let them shut the doors, and bar them: and appoint watches of the inhabitants of Jerusalem, every one in his watch, and every one to be over against his house., [1, 1])
(Nehemiah 7:4 Now the city was large and great: but the people were few therein, and the houses were not builded., [])
(Nehemiah 7:5 And my God put into mine heart to gather together the nobles, and the rulers, and the people, that they might be reckoned by genealogy. And I found a register of the genealogy of them which came up at the first, and found written therein,, [1])
(Nehemiah 7:6 These are the children of the province, that went up out of the captivity, of those that had been carried away, whom Nebuchadnezzar the king of Babylon had carried away, and came again to Jerusalem and to Judah, every one unto his city;, [1])
(Nehemiah 7:7 Who came with Zerubbabel, Jeshua, Nehemiah, Azariah, Raamiah, Nahamani, Mordecai, Bilshan, Mispereth, Bigvai, Nehum, Baanah. The number, I say, of the men of the people of Israel was this;, [])
(Nehemiah 7:8 The children of Parosh, two thousand an hundred seventy and two., [2172])
(Nehemiah 7:9 The children of Shephatiah, three hundred seventy and two., [372])
(Nehemiah 7:10 The children of Arah, six hundred fifty and two., [652])
(Nehemiah 7:11 The children of Pahathmoab, of the children of Jeshua and Joab, two thousand and eight hundred and eighteen., [2818])
(Nehemiah 7:12 The children of Elam, a thousand two hundred fifty and four., [1254])
(Nehemiah 7:13 The children of Zattu, eight hundred forty and five., [845])
(Nehemiah 7:14 The children of Zaccai, seven hundred and threescore., [760])
(Nehemiah 7:15 The children of Binnui, six hundred forty and eight., [648])
(Nehemiah 7:16 The children of Bebai, six hundred twenty and eight., [628])
(Nehemiah 7:17 The children of Azgad, two thousand three hundred twenty and two., [2322])
(Nehemiah 7:18 The children of Adonikam, six hundred threescore and seven., [667])
(Nehemiah 7:19 The children of Bigvai, two thousand threescore and seven., [2067])
(Nehemiah 7:20 The children of Adin, six hundred fifty and five., [655])
(Nehemiah 7:21 The children of Ater of Hezekiah, ninety and eight., [98])
(Nehemiah 7:22 The children of Hashum, three hundred twenty and eight., [328])
(Nehemiah 7:23 The children of Bezai, three hundred twenty and four., [324])
(Nehemiah 7:24 The children of Hariph, an hundred and twelve., [112])
(Nehemiah 7:25 The children of Gibeon, ninety and five., [95])
(Nehemiah 7:26 The men of Bethlehem and Netophah, an hundred fourscore and eight., [188])
(Nehemiah 7:27 The men of Anathoth, an hundred twenty and eight., [128])
(Nehemiah 7:28 The men of Bethazmaveth, forty and two., [42])
(Nehemiah 7:29 The men of Kirjathjearim, Chephirah, and Beeroth, seven hundred forty and three., [743])
(Nehemiah 7:30 The men of Ramah and Gaba, six hundred twenty and one., [621])
(Nehemiah 7:31 The men of Michmas, an hundred and twenty and two., [122])
(Nehemiah 7:32 The men of Bethel and Ai, an hundred twenty and three., [123])
(Nehemiah 7:33 The men of the other Nebo, fifty and two., [52])
(Nehemiah 7:34 The children of the other Elam, a thousand two hundred fifty and four., [1254])
(Nehemiah 7:35 The children of Harim, three hundred and twenty., [320])
(Nehemiah 7:36 The children of Jericho, three hundred forty and five., [345])
(Nehemiah 7:37 The children of Lod, Hadid, and Ono, seven hundred twenty and one., [721])
(Nehemiah 7:38 The children of Senaah, three thousand nine hundred and thirty., [3930])
(Nehemiah 7:39 The priests: the children of Jedaiah, of the house of Jeshua, nine hundred seventy and three., [973])
(Nehemiah 7:40 The children of Immer, a thousand fifty and two., [1052])
(Nehemiah 7:41 The children of Pashur, a thousand two hundred forty and seven., [1247])
(Nehemiah 7:42 The children of Harim, a thousand and seventeen., [1017])
(Nehemiah 7:43 The Levites: the children of Jeshua, of Kadmiel, and of the children of Hodevah, seventy and four., [74])
(Nehemiah 7:44 The singers: the children of Asaph, an hundred forty and eight., [148])
(Nehemiah 7:45 The porters: the children of Shallum, the children of Ater, the children of Talmon, the children of Akkub, the children of Hatita, the children of Shobai, an hundred thirty and eight., [138])
(Nehemiah 7:46 The Nethinims: the children of Ziha, the children of Hashupha, the children of Tabbaoth,, [])
(Nehemiah 7:47 The children of Keros, the children of Sia, the children of Padon,, [])
(Nehemiah 7:48 The children of Lebana, the children of Hagaba, the children of Shalmai,, [])
(Nehemiah 7:49 The children of Hanan, the children of Giddel, the children of Gahar,, [])
(Nehemiah 7:50 The children of Reaiah, the children of Rezin, the children of Nekoda,, [])
(Nehemiah 7:51 The children of Gazzam, the children of Uzza, the children of Phaseah,, [])
(Nehemiah 7:52 The children of Besai, the children of Meunim, the children of Nephishesim,, [])
(Nehemiah 7:53 The children of Bakbuk, the children of Hakupha, the children of Harhur,, [])
(Nehemiah 7:54 The children of Bazlith, the children of Mehida, the children of Harsha,, [])
(Nehemiah 7:55 The children of Barkos, the children of Sisera, the children of Tamah,, [])
(Nehemiah 7:56 The children of Neziah, the children of Hatipha., [])
(Nehemiah 7:57 The children of Solomon's servants: the children of Sotai, the children of Sophereth, the children of Perida,, [])
(Nehemiah 7:58 The children of Jaala, the children of Darkon, the children of Giddel,, [])
(Nehemiah 7:59 The children of Shephatiah, the children of Hattil, the children of Pochereth of Zebaim, the children of Amon., [])
(Nehemiah 7:60 All the Nethinims, and the children of Solomon's servants, were three hundred ninety and two., [392])
(Nehemiah 7:61 And these were they which went up also from Telmelah, Telharesha, Cherub, Addon, and Immer: but they could not shew their father's house, nor their seed, whether they were of Israel., [])
(Nehemiah 7:62 The children of Delaiah, the children of Tobiah, the children of Nekoda, six hundred forty and two., [642])
(Nehemiah 7:63 And of the priests: the children of Habaiah, the children of Koz, the children of Barzillai, which took one of the daughters of Barzillai the Gileadite to wife, and was called after their name., [1])
(Nehemiah 7:64 These sought their register among those that were reckoned by genealogy, but it was not found: therefore were they, as polluted, put from the priesthood., [])
(Nehemiah 7:65 And the Tirshatha said unto them, that they should not eat of the most holy things, till there stood up a priest with Urim and Thummim., [])
(Nehemiah 7:66 The whole congregation together was forty and two thousand three hundred and threescore,, [42360])
(Nehemiah 7:67 Beside their manservants and their maidservants, of whom there were seven thousand three hundred thirty and seven: and they had two hundred forty and five singing men and singing women., [7337, 245])
(Nehemiah 7:68 Their horses, seven hundred thirty and six: their mules, two hundred forty and five:, [736, 245])
(Nehemiah 7:69 Their camels, four hundred thirty and five: six thousand seven hundred and twenty asses., [441720])
(Nehemiah 7:70 And some of the chief of the fathers gave unto the work. The Tirshatha gave to the treasure a thousand drams of gold, fifty basons, five hundred and thirty priests' garments., [1000, 50, 530])
(Nehemiah 7:71 And some of the chief of the fathers gave to the treasure of the work twenty thousand drams of gold, and two thousand and two hundred pound of silver., [20000, 2200])
(Nehemiah 7:72 And that which the rest of the people gave was twenty thousand drams of gold, and two thousand pound of silver, and threescore and seven priests' garments., [20000, 2000, 67])
(Nehemiah 7:73 So the priests, and the Levites, and the porters, and the singers, and some of the people, and the Nethinims, and all Israel, dwelt in their cities; and when the seventh month came, the children of Israel were in their cities., [7])
[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
>>> 
>>> 
>>> 
>>> b/666
1 Kings 10:14;2 Chronicles 9:13;Ezra 2:13;Revelation 13:18 (4 verses)
>>> 
